### ISSUE TITLE
php*-zlib no longer available

### ISSUE THREAD

**Issue by jimsihk** [TrafeX/docker-php-nginx#103]
Hi, I found that php*-zlib is no longer available since alpine 3.7, seems it should be removed from Dockerfile?

Search from alpine package portal:
https://pkgs.alpinelinux.org/packages?name=php*zlib&branch=v3.16&repo=&arch=&maintainer=

Last available version: 
https://pkgs.alpinelinux.org/packages?name=php*zlib&branch=v3.7&repo=&arch=&maintainer=

**Comment by TrafeX** [comment]
Hi @jimsihk ,

You're right, I've removed it: https://github.com/TrafeX/docker-php-nginx/commit/0be32d31319b0e5f81850f9ef11db2e0b9446092
Thank you!
