### ISSUE TITLE
What's best way to edit Nginix configuration in /etc/nginx/ (similarly php-setting.ini)?

### ISSUE THREAD

**Issue by chotalia** [TrafeX/docker-php-nginx#104]
As an example if I want to use the different root folder i.e. instead of  /var/www/html using /var/www/www.domain.com and two or three other settings.

1. Should I copy the config in different folder and then mount using /nginx-server.conf when starting the container?
Where is the alternative location for the config generally?

2. Or fork the repo, edit the config?

Or am I missing some other better ways?

**Comment by TrafeX** [comment]
Hi @chotalia,

This project should be an example which you can fork or copy to your own project and modify to your needs. So option 2.
