### ISSUE TITLE
How can we add PHP PDO?

### ISSUE THREAD

**Issue by trd** [TrafeX/docker-php-nginx#107]
I've tried in multiple ways, but none of them worked. Does anybody have an idea about how to add the PDO extension for MySQL? Thank you.

**Comment by TrafeX** [comment]
Hi @trd ,

You need to add the `php81-pdo_mysql` package to the `apk add` command here: https://github.com/TrafeX/docker-php-nginx/blob/master/Dockerfile#L9

**Comment by trd** [comment]
Thank you.
