### ISSUE TITLE
Running Laravel / Lumen gives unstable worker queue

### ISSUE THREAD

**Issue by we-care-tech** [TrafeX/docker-php-nginx#108]
We have adapted this setup for laravel / lumen frameworks, and everything works great except one thing.

We have added to the Dockerfile:
```
# Install composer from the official image
COPY --from=composer /usr/bin/composer /usr/bin/composer
# Run composer install to install the dependencies
RUN composer install --optimize-autoloader --no-interaction --no-progress --ignore-platform-req=ext-sodium
RUN composer update
RUN composer dump-autoload -o
# migrate
RUN php artisan migrate
```
This works great.

And then to supervisor I added:
```
[program:laravel-queue]
numprocs=3
autostart=true
autorestart=true
redirect_stderr=true
user=nobody
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/var/log/nginx/worker.log
command=/usr/bin/php /var/www/html/artisan queue:work sqs --tries=3 --timeout=90 --queue=default
```

But the worker is very unstable. Some jobs run, some does not.
Any ideas?

**Comment by TrafeX** [comment]
Hi @we-care-tech,

Do you get any output in the `worker.log` or the container log?
Could you try to run only 1 worker for a while to see if that makes it more stable?

**Comment by TrafeX** [comment]
@we-care-tech ah that explains. Glad you solved it!
