### ISSUE TITLE
Add a persistent storage

### ISSUE THREAD

**Issue by Nottt** [TrafeX/docker-php-nginx#11]
Would be possible to add a volume so we could interact with the contents of `/var/www/html` on the host, and also persist it between machines?

Example, I have a php script where you run `install.php`, and then after that you are supposed to remove the file from `/var/www/html` and also change permission of other files to make it more secure.

This image work wonderfully for fully static php scripts, but even for them, you still need to fork this repo, add your own files to `/scr` and then create a container in hubdocker to make it work. You may not want to have this public.

With persistent storage, all you'd need to do is to map something like `/opt/website` to `/var/www/html` inside of the container, and it would work out of the box.

**Comment by TrafeX** [comment]
Thanks for the suggestion, that is a good idea! I added it in https://github.com/TrafeX/docker-php-nginx/commit/e829a11c932835d52df563f9d1600d10900e755f

**Comment by Nottt** [comment]
Thanks! 

If you don't know already, I'd like to introduce you to s6-overlay. It's like your supervisor but I think it's easier and more flexible. Might be useful in future projects.

I see you went straight to mapping to /var/www/html, i remember this used to cause issues with docker if you are still copying /src to it, did it work okay in the tests?

In my fork, I just created the folder /config and symlinked it to /var/www/html

**Comment by TrafeX** [comment]
I know of s6-overlay, it's a better fit for Docker containers indeed. I didn't chose it when I created this image because installation was a hassle. But nowadays that's quite easy so I might switch to it in the future.

The mapping is fine, the copy is done during the build, but the volume is mounted during runtime and overrules the files that were copied in the image. You just need to be aware of the permissions. The `nobody` user should have the permissions you want on the mount.

**Comment by Nottt** [comment]
If you want templates you can take a look at my deluge [dockerfile](https://github.com/Nottt/deluge/blob/master/Dockerfile), and if you have any questions you can ping me.

I have a working website now and the files are owned by root, I think it's fine as long you have read access to everyone.

If you want to make it more robust, you can do like I do in my dockers with s6, change the PID and UID of the user inside the container to a variable given in runtime. Not sure if that's possible with the supervisor you use.
