### ISSUE TITLE
Question about "Optimized for 100 concurrent users"

### ISSUE THREAD

**Issue by foremtehan** [TrafeX/docker-php-nginx#112]
Hey man first i want to thanks you for working on the repo.

I wanna know about "Optimized for 100 concurrent users" you mentioned in the readme, Does it mean it restricted to only handle 100 concurrent users or is it depends on my resources ?

**Comment by TrafeX** [comment]
Hi @foremtehan,

That mainly refers to to the `max_children` setting in PHP-FPM: https://github.com/TrafeX/docker-php-nginx/blob/master/config/fpm-pool.conf#L33
This limits the number of concurrent requests that PHP-FPM can handle to 100.
Other factors are in play as well, you indeed need to have enough resources. But that fully depends on the type of application you're running via this container.
