### ISSUE TITLE
How enable extensions php?

### ISSUE THREAD

**Issue by auguzsto** [TrafeX/docker-php-nginx#113]
Hi, guys! How do enable some extensions php?

**Comment by ExerciseBook** [comment]
add it to dockerfile and rebuild (确信)

**Comment by ExerciseBook** [comment]
https://github.com/ParaParty/docker-php-nginx this is my example, you can refer to it.

Hope helps.

**Comment by TrafeX** [comment]
Hi @auguzsto,

I hope the answers of @ExerciseBook helped you in the right direction. It's indeed needed to make the changes in the Dockerfile yourself.
