### ISSUE TITLE
Cache management

### ISSUE THREAD

**Issue by marcellov7** [TrafeX/docker-php-nginx#114]
Hi, 
congratulations for the project, I found it really very useful.

Is there already a cache management in this project?
Otherwise what would you recommend me to integrate fastCGI cache or memcache?

Thank you

**Comment by TrafeX** [comment]
Hi @marcellov7,

Thank you! There is no cache management in this project. I would recommend to pick a system that's designed for this purpose. I have good experience with Memcache and Redis, both have good Docker containers which you can get up&running in minutes.

**Comment by marcellov7** [comment]
> Hi @marcellov7,
> 
> Thank you! There is no cache management in this project. I would recommend to pick a system that's designed for this purpose. I have good experience with Memcache and Redis, both have good Docker containers which you can get up&running in minutes.

Thanks 👍
