### ISSUE TITLE
Add ioncube php module

### ISSUE THREAD

**Issue by Nottt** [TrafeX/docker-php-nginx#12]
I tried to serve a website with this docker but I got this error:

```
Site error: the ionCube PHP Loader needs to be installed. This is a widely used PHP extension for running ionCube protected PHP code, website security and malware blocking. 

Please visit get-loader.ioncube.com for install assistance.
```

I can do a pull request if you wish so.

**Comment by TrafeX** [comment]
Hi Nott,

This extension is a bit out of scope for this container image. The image is meant to be an example/blueprint for running Nginx & PHP-FPM in a container, I've included some general PHP extensions so you can do the basics. But if you want more I suggest to fork it and create your own variant for you specific needs.

If you add these lines to your image you're probably good to go;
https://github.com/ipburger/php7.2-ioncube-alpine.docker/blob/master/Dockerfile#L3-L9

Cheers

**Comment by Nottt** [comment]
ok, can you at least add php7-session? it's required for a lot of websites

**Comment by TrafeX** [comment]
It's added :+1: https://github.com/TrafeX/docker-php-nginx/releases/tag/1.2.0
