### ISSUE TITLE
introducing new config file is a breaking change

### ISSUE THREAD

**Issue by ThetaGamma** [TrafeX/docker-php-nginx#120]
hi all
FYI, the newest release (2.7.0) introduces an config file `"/etc/nginx/conf.d/default.conf"` which breaks (at least my) installation, as it contains the configuration of a default server.

with previously releases I just overwrote the shipped nginx.conf with my own version in docker-compose like this:

```
volumes:
      - /home/me/Docker/nginxphp/config/0_default.conf:/etc/nginx/conf.d/0_default.conf
      - /home/me/Docker/nginxphp/config/nginx.conf:/etc/nginx/nginx.conf

```
now I have to overwrite like this:
```
volumes:
      - /home/me/Docker/nginxphp/config/0_default.conf:/etc/nginx/conf.d/0_default.conf
      - /home/me/Docker/nginxphp/config/conf.d/default.conf:/etc/nginx/conf.d/default.conf

```

No big prob and it was easy to solve, but perhaps worth mentioning in the release notes, that others are aware

**Comment by TrafeX** [comment]
Hi @ThetaGamma,

You're right, I also had a [simulair issue](https://github.com/TrafeX/docker-php-nginx/issues/119) reported.
So I pulled the 2.7.0 release and made it a [3.0.0](https://github.com/TrafeX/docker-php-nginx/releases/tag/3.0.0) with notes about the breaking changes.

Thank you for the headsup!
