### ISSUE TITLE
`max_execution_time` not getting applied in php.ini

### ISSUE THREAD

**Issue by foremtehan** [TrafeX/docker-php-nginx#123]
This is my php.ini file:

```
[PHP]
max_execution_time = 59

[Date]
date.timezone="UTC"
expose_php= Off
```
Dockerfile:

```
COPY docker-config/php.ini /etc/php81/conf.d/custom.ini
```

Inside the container:

![image](https://user-images.githubusercontent.com/53290883/212646309-7cb74aef-3369-455f-b819-97460be3724e.png)

But looks like it did not applied :

![image](https://user-images.githubusercontent.com/53290883/212933064-bb44e453-b306-431b-b35f-a73cc8342b68.png)

I also removed the keyword `[PHP]` but didn't work either

**Comment by foremtehan** [comment]
my bad

**Comment by TrafeX** [comment]
Hi @foremtehan,

I believe this is because `artisan` overrides the `max_execution_time` to set it to unlimited for CLI commands.

**Comment by foremtehan** [comment]
I don't think so, Here is the artisan file https://github.com/laravel/laravel/blob/9.x/artisan

**Comment by TrafeX** [comment]
You're right, I forgot that PHP overrides a few settings when using the CLI; https://www.php.net/manual/en/features.commandline.differences.php
As the docs said, these settings cannot be changed via ini files, you can only override it in the code with `init_set`.
