### ISSUE TITLE
PHP 8.2 support?

### ISSUE THREAD

**Issue by DrH97** [TrafeX/docker-php-nginx#127]
Hey @TrafeX,

Is there a plan for 8.2 support?

**Comment by TrafeX** [comment]
Hi @DrH97,

The image is based on Alpine Linux and uses the precompiled package from it for PHP.
They have PHP8.2 support in their 'edge' repositories but it's not yet included in a stable release, so we're waiting for that.
They release every 6 months approx, so I expect a new release somewhere in May 2023.

**Comment by DrH97** [comment]
Alright, Thanks for the info.
