### ISSUE TITLE
php-fpm error

### ISSUE THREAD

**Issue by realspinelle** [TrafeX/docker-php-nginx#130]
![image](https://github.com/TrafeX/docker-php-nginx/assets/39035551/c84f533c-7b97-4b31-9843-c21fd07b1a36)

my Dockerfile
FROM trafex/php-nginx
EXPOSE 3000
USER root
RUN rm /etc/nginx/conf.d/default.conf
COPY ./ptero.conf /etc/nginx/conf.d/ptero.conf

**Comment by umneeq2** [comment]
The same here...

**Comment by TrafeX** [comment]
Hi @realspinelle & @umneeq2 ,

This image is optimized to run as a non-privileged user. So just remove the `USER root` line and it should work :+1:

**Comment by TrafeX** [comment]
I assume the issue is resolved, let me know if that's not the case!
