### ISSUE TITLE
PHP 8.2

### ISSUE THREAD

**Issue by C0mp4ct** [TrafeX/docker-php-nginx#134]
Hi, ty for great image, could you please update PHP to 8.2 as it's now in stable alpine repository.

Thanks!

**Comment by TrafeX** [comment]
Hi @C0mp4ct ,

Yes I'll pick this up soon!

**Comment by TrafeX** [comment]
@C0mp4ct Here it is! https://github.com/TrafeX/docker-php-nginx/releases/tag/3.2.0
