### ISSUE TITLE
Sendmail support?

### ISSUE THREAD

**Issue by imp1sh** [TrafeX/docker-php-nginx#140]
Hi,

websites often have contact forms or alike.
What is your concept for such situations. I tried to use a wordpress form and it said:

sendmail: can't connect to remote host (127.0.0.1): Connection refused

Thanks for you help

**Comment by imp1sh** [comment]
I added a pull request
https://github.com/TrafeX/docker-php-nginx/pull/142

**Comment by TrafeX** [comment]
As mentioned in the PR; I'm not adding this in the minimal setup this Docker container has, instead I've described your example in the documentation: https://github.com/TrafeX/docker-php-nginx/blob/master/docs/sending-emails.md
