### ISSUE TITLE
Where is the tokenizer.so??

### ISSUE THREAD

**Issue by sunceenjoy** [TrafeX/docker-php-nginx#148]
The module **tokenizer** in php8.2 is configured as a shared module, So by default, **php -m** does not list this extension, I will need to add this to php.ini: **extension=tokenizer**, but I don't find the so file in this folder: /usr/lib/php82/modules/
What should I do?

![image](https://github.com/TrafeX/docker-php-nginx/assets/3994120/6c586a80-39ce-40b2-ba2a-25cedc301658)
![image](https://github.com/TrafeX/docker-php-nginx/assets/3994120/c972385d-9445-4ad6-bb38-384c1a89d5d2)

**Comment by TrafeX** [comment]
Hi @sunceenjoy,

That extension should indeed be part of the base extensions this image has. It's added by @insign and can be used in the `latest` tag.
