### ISSUE TITLE
Tag by php version

### ISSUE THREAD

**Issue by insign** [TrafeX/docker-php-nginx#150]
Can you automate tagging by php version? Because I would like to use latest but someday it will change to php 8.3 which can cause problems to who tested his projects in php 8.2

**Comment by TrafeX** [comment]
I'm following 'semantic versioning' to make sure you don't get any breaking changes when updating a minor version. So when the image gets updated to, for instance, PHP 8.3, a new minor version will be released.
I currently have no plans to support multiple PHP versions.
