### ISSUE TITLE
supervisorctl not working

### ISSUE THREAD

**Issue by jduan00** [TrafeX/docker-php-nginx#161]
Hi there!

After getting into the image:
`$ docker exec -it -u root container sh`

The following cmd fails:
`# supervisorctl`
`unix:///run/supervisord.sock no such file`

Any thoughts to fix it? Thanks!

**Comment by TrafeX** [comment]
Hi @jduan00 ,

That's because the socket isn't configured in `supervisord.conf`. I don't directly see why this would be needed.
But you can add it yourself by configuring a unix http server: http://supervisord.org/configuration.html#unix-http-server-section-settings

**Comment by jduan00** [comment]
Hi @TrafeX 

Happy New Year 2024! I agree. After looking into this more, I realize it is better to leave it alone to KISS. Thanks for getting back. Cheers!
