### ISSUE TITLE
docker-php-nginx with PHP 8.3?

### ISSUE THREAD

**Issue by bu6n** [TrafeX/docker-php-nginx#165]
Hi,
Just wanted to ask if you plan to make a version with PHP 8.3? 
I'm especially interested in the new feature of reading environment variables in .ini files with a default value (https://php.watch/versions/8.3/php-ini-envar-fallback-value-syntax), which could be really useful in the context of docker containers.

As I understand it, php 8.3 will probably be in the May release of alpine linux, so we can probably wait until then. The php83 packages seem to already be present in `alpine-edge`.

**Comment by TrafeX** [comment]
Hi @bu6n,

As a matter of fact, it was part of the Alpine Linux 3.19 release from December: https://www.alpinelinux.org/posts/Alpine-3.19.0-released.html
So, here's PHP8.3: https://github.com/TrafeX/docker-php-nginx/releases/tag/3.5.0 :tada:
