### ISSUE TITLE
Providing a volume where the public index/root should be a child directory

### ISSUE THREAD

**Issue by polarathene** [TrafeX/docker-php-nginx#17]
If you create a standard laravel project, only the `project/public/` sub-directory should be exposed, while it's index.php will reference content from the projects sibling directories via the php process.

What's the advised way for handling this? Modifying the root in the `nginx.conf`? Or is there some other way to be more flexible with the the project path? 

I suppose I could mount the volume to `/var/www` and change `/public` to `/html` on the host filesystem?

**Comment by polarathene** [comment]
Perhaps splitting the config like handled in [this project](https://github.com/Stolz/laravel-docker-stack/blob/master/nginx/config/servers.conf) would make sense? They have a very small server conf and include conf files for the rest.

It looks like you could just do the reverse, and include a conf file for the server root? Easy to override then.

**Comment by TrafeX** [comment]
Hi Brennan,

Thank you for your suggestion! The original idea for this image was to make it an example how you can setup a container image with Nginx & PHP-FPM using some best practices and keep it as simple as possible. So I intentionally left out a 'modular config' setup to keep it straight forward and easy to understand for everyone. If you want to change something (and you probably need to) then you can fork it or copy it to your own setup.

But I see that more and more people are using this image as it is because it already covers some use cases. So I need to change this strategy a bit to still have it as an example but also making it a bit easier to extend while still being able to update when I push new changes.
I'm already working on that and will update this image soon.

For your case; indeed, changing the root in `nginx.conf` would be the way to go.

**Comment by TrafeX** [comment]
I'll close this issue. If you have any questions, just re-open it!

**Comment by polarathene** [comment]
I'm not able to re-open the issue as I don't have permission. How do you feel with the earlier suggestion of breaking out some of the nginx.conf file into smaller conf files? You did state that you were working towards an update that might accommodate that?

For the issue in #16 I was able to just add an `include ./adjustments/http.conf;` into the `nginx.conf` `http{}` block, I placed it after the `include mime.types;` line and mounted the file from host to `/etc/nginx/adjustments/http.conf`. Nginx required all 5 paths to be adjusted to the `/tmp` location as shown in the linked issue(exact content of the file), then it would start successfully without permission errors on older kernels.

---

Would you like me to submit a PR that adds an include block for user additions in `/etc/nginx/adjustments`? And/or splitting the config for http and server blocks? Something like [the earlier referenced project](https://github.com/Stolz/laravel-docker-stack/tree/master/nginx/config), which is pretty nice(except the fastgi.conf/mime.types files, those can be ignored, as they are included by default with nginx, I'm not sure why the project adds them).

**Comment by TrafeX** [comment]
Hi Brennan,

Thanks for your input! I've done some changes that hopefully help you. 
First I've changed the temporary/cache paths in Nginx to `/tmp` to resolve https://github.com/TrafeX/docker-php-nginx/issues/16
Nginx recommends this for their own image as well; https://hub.docker.com/_/nginx

Secondly, I've added an `Include /etc/nginx/conf.d/*.conf` to [nginx.conf](https://github.com/TrafeX/docker-php-nginx/blob/master/config/nginx.conf#L87) that allows you to extend the config by mounting files in that folder.
For example; `docker run -v "myconfig.conf:/etc/nginx/conf.d/myconfig.conf" ...`

I've not broken down the config in separate files to keep it simple and easy to understand.
Let me know if this works for you!

**Comment by TrafeX** [comment]
I'll close this issue. If you have any questions, let me know!

**Comment by auchri** [comment]
Hi, sorry for commenting on this old issue but I have a question:
How can I change the root-folder of nginx? I've already mounted a file (like `-v "myconfig.conf:/etc/nginx/conf.d/myconfig.conf"`) but now my nginx fails to start because of the invalid configuration in there :D
