### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by rogeriolino** [TrafeX/docker-php-nginx#18]
Add `tzdata` package to enable timezone definition via environment variable (TZ).

edit: update php.ini from env too.

**Comment by TrafeX** [comment]
Hi Rogério,

Why do you want to change the timezone in the container? Most of the time it's better to leave the OS time on UTC and only set a specific timezone in the application you're using.

Making the timezone in the PHP.ini configuration dynamic based on an environment variable is a bit out of scope for this image. I try to keep the config simple without any magic so it serves as an template.

If you want to configure a different timezone it's best to fork this repository and build your own container (you probably need to tweak some other settings as well).

**Comment by rogeriolino** [comment]
That was a requirement that I had. But you're right, I'm agreeing with you.

Regards
