### ISSUE TITLE
Missing PDO

### ISSUE THREAD

**Issue by BloomyInDev** [TrafeX/docker-php-nginx#180]
Hey,
I've started to use your container but it seems that you don't have installed the optional package `php81-pdo` so i can't use the PDO class.
Can you add it to the container ?
Have a good day

**Comment by BloomyInDev** [comment]
If you want, i can make a pull request to add this

**Comment by TrafeX** [comment]
Hi @BloomyInDev ,

Thank you for the suggestion. This container is meant as an example which you copy and paste to adjust to your needs. 
Therefore, it's not a all-in-one solution that has all the PHP extensions and I don't want to add more.
You can either extend from this image and install the needed extensions in your own image, or completely copy/paste it.

**Comment by fermino** [comment]
@BloomyInDev example dockerfile

```
FROM trafex/php-nginx:latest

USER root
RUN apk add --no-cache php83-pdo_mysql php83-pdo_sqlite # plus whatever other extensions you need

USER nobody
```

**Comment by BloomyInDev** [comment]
I already did a clone. It was just if it was intentional or not

Anyway thanks

**Comment by haldi4803** [comment]
> @BloomyInDev example dockerfile
> 
> ```
> FROM trafex/php-nginx:latest
> 
> USER root
> RUN apk add --no-cache php83-pdo_mysql php83-pdo_sqlite # plus whatever other extensions you need
> 
> USER nobody
> ```

How would one go about using that with Docker-Compose.yaml ?

**Comment by BloomyInDev** [comment]
> > @BloomyInDev example dockerfile
> > ```
> > FROM trafex/php-nginx:latest
> > 
> > USER root
> > RUN apk add --no-cache php83-pdo_mysql php83-pdo_sqlite # plus whatever other extensions you need
> > 
> > USER nobody
> > ```
> 
> How would one go about using that with Docker-Compose.yaml ?

This is a `Dockerfile` so you need to build it before

**Comment by haldi4803** [comment]
No you dont.

´´´version: "3.8"

services:

  app:
    image: trafex/php-nginx
    container_name: containername
    user: root
    command: sh -c "apk add --no-cache php84-pdo_mysql php84-pdo"
    ports:
      - "8080:8080"
    volumes:
      - /mnt/docker/web:/var/www/html
    restart: always
´´´

You just need to make sure to use correct phpt version... 8.3 or 8.4 for current build.

**Comment by BloomyInDev** [comment]
that another way, i prefer doing it the dockerfile way cuz it wont redo the installation of some packages (here pdo_mysql and pdo)
