### ISSUE TITLE
Image Built Is larger than expected

### ISSUE THREAD

**Issue by yunus89** [TrafeX/docker-php-nginx#19]
Hi @TrafeX 

According to the docs at readme file, the image size if ought to be  -/+35MB, although when i clone and run `docker build -t trafex .`, the image builds successful but with a whopping 110MB.

    Very small Docker image size (+/-35MB)

How can the image size be reduced to `35MB` and still be able to run a Laravel/Lumen application ?

Thanks

**Comment by TrafeX** [comment]
Hi @yunus89,

What you see locally is the uncompressed size. The +/- 35MB refers to the compressed size, the amount of data you need to download. You see that amount here as well: https://hub.docker.com/r/trafex/alpine-nginx-php7/tags

I'm afraid I can't make the image smaller than it is. Most of the storage is needed for these packages; https://github.com/TrafeX/docker-php-nginx/blob/master/Dockerfile#L6-L8 
Maybe you can have a look at it to see if you can remove a few for your application, that will save you some MB's.
