### ISSUE TITLE
/var/www/html permissions

### ISSUE THREAD

**Issue by peschee** [TrafeX/docker-php-nginx#22]
Hi

I'm trying to use your image as a base for building my application image. However, I noticed that the way permissions of `/var/www/html` are setup it is impossible to interact with the contents of that folder with user `nobody`.

Here's a simple example of a custom `Dockerfile`:

```
FROM trafex/alpine-nginx-php7:1.3.0

RUN echo "Hello" > hello.html
```

This fails with `/bin/sh: can't create hello.html: Permission denied`.

Is this desired behaviour?

**Comment by palchik1985** [comment]
Hi
I had the same problem. The resolve - below:

Check of owner of your project files on the local machine. You can see this with command 
`ls -la`. You should to change owner ID on your local machine and set the same as in docker container (user nobody with ID 1000):

`chown -R 1000:1000 /path/to/your/project`

In docker container you have the not ROOT user, but nobody with ID 1000 and lowest permissions.

Perhaps, on your local machine you have files owned by the ROOT user with full permissions. Files owned by ROOT can't be changed by user nobody with ID 1000.
This needs for security, cause hacker who have a control on your site - will have not root permissions and couldn't change any files outside of your project.

So you need just to change owner of files, and problem will be fixed.

**Comment by peschee** [comment]
>You should to change owner ID on your local machine and set the same as in docker container

This is not really an option. I don't want to set permissions to `1000:1000` on my local files.

Also, the files used in `COPY` are owned by my user, not root

**Comment by palchik1985** [comment]
> Also, the files used in `COPY` are owned by my user, not root

So, this is security issue for the SERVER containers. As I see, you try to do that on your local machine? So you have cheat this system.

You can change ID of user nobody on the docker container to the same ID as your local user.

Most likely, your local user has ID 1000. So you can change nobody's user ID in the docker container to 1000, and all will good work

**Comment by palchik1985** [comment]
This is my example of a Dockerfile for the local work: 
`
FROM composer:latest AS composer
FROM trafex/alpine-nginx-php7

COPY --from=composer /usr/bin/composer /usr/bin/composer

user root

#need for same folder rights as local user
RUN apk --no-cache add shadow && \
    usermod -u 1000 nobody; \
    groupmod -g 1000 nobody;

RUN apk --update --no-cache add php7-xdebug php7-tokenizer php7-fileinfo \
    php7-pdo php7-pdo_mysql php7-session
    
    
user nobody

# Add application
WORKDIR /var/www/queen

# Expose the port nginx is reachable on
EXPOSE 8080

# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

# Configure a healthcheck to validate that everything is up&running
HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/fpm-ping`

**Comment by TrafeX** [comment]
Hi @peschee ,

The `/var/www/html` folder is owned by `root`. The problem is that when you extend from this image, you also take over the `user` which is set to `nobody`: https://github.com/TrafeX/docker-php-nginx/blob/master/Dockerfile#L35
That means every command you add in your Dockerfile will run under the `nobody` user. And since the folder you try to write to is owned by `root` you get a permission error.

You can resolve this by doing it like @palchik1985 does, switch to the `root` user, execute the necessary commands and switch back to the `nobody` user in the end.

**Comment by TrafeX** [comment]
I'll close this issue. If you have any questions, let me know!

**Comment by peschee** [comment]
@TrafeX Thanks for getting back to me.

Let me restate my problem: I currently don't see a way on how to interact with the contents of `/var/www/html` at runtime when the user is `nobody`.

Consider this simple example:

I have a `Dockerfile`:

```
FROM trafex/alpine-nginx-php7:1.3.0

USER root

COPY ./docker/entrypoint.sh /usr/local/bin

USER nobody

ENTRYPOINT ["entrypoint.sh"]
```

and a `entrypoint.sh` file:

```sh
#!/bin/sh
set -e

echo bar > foo.html

exec "$@"
```

The resulting container does not run. It fails with `/usr/local/bin/entrypoint.sh: line 4: can't create foo.html: Permission denied`

An even simpler use case would be to have the following `Dockerfile`:

```
FROM trafex/alpine-nginx-php7:1.3.0
```

then run the resulting container with `docker run -it --entrypoint /bin/sh your-image-name`. Inside the container, it is not possible to create any files within the `/var/www/html` directory with the `nobody` user:

```
/var/www/html $ touch test
touch: test: Permission denied
```

I'm not sure how to work around this issue. I assume the problem is that the directory `/var/www/html` is explicitly created as a `VOLUME` in a previous layer and the directory belongs to root. Hence, the ownership of `/var/www/html` cannot be changed to e.g. `nobody`. I'm also not sure why you'd need this volume instruction in the Dockerfile https://github.com/TrafeX/docker-php-nginx/blob/master/Dockerfile#L32 since volumes can be mounted without this.

Does this make more sense?

**Comment by TrafeX** [comment]
Hi @peschee,

I see what you mean and I think it makes sense to have `/var/www/html` owned by the `nobody` user as well. I changed this in master. Can you see if this resolves your problem by using `trafex/alpine-nginx-php7:latest`?

**Comment by peschee** [comment]
Hey @TrafeX 

Yes, this seems to solve my permission issues. However, I have this simple test case and the container does not seem to run properly:

`Dockerfile`

```Dockerfile
FROM trafex/alpine-nginx-php7:latest

COPY --chown=nobody ./entrypoint.sh /usr/local/bin

RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]
```

`entrypoint.sh`

```sh
#!/bin/sh
set -e

echo bar > foo.html

exec "$@"
```

When I build and run the container with

`$ docker build -t test . && docker run -p 30000:80 test`

it does not run nor does it show any errors. Any idea why? Maybe an issue with `exec "$@"` inside the entrypoint script?

**Comment by TrafeX** [comment]
Hi @peschee,

Where you able to resolve this? I've gave it a try but came to the same result as you had. I can dive into it if you still run into this issue.

**Comment by peschee** [comment]
@TrafeX Well no, the issue as per my last comment unfortunately still remains. If you could have a look at that minimal test case, that would be awesome.

**Comment by TrafeX** [comment]
@peschee You need to include the `CMD` from the parent image in yours;
```
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
```
I believe because you define an ENTRYPOINT the CMS is reset to it's default value. Adding the CMD will successfully start the container in my test.

**Comment by peschee** [comment]
@TrafeX thank you for your feedback. indeed setting the `CMD` instruction in my `Dockerfile` works. I have created a repository with the simple test case from this issue at https://github.com/peschee/docker-php-nginx-test
