### ISSUE TITLE
Concurrent Users

### ISSUE THREAD

**Issue by synetalsolutions** [TrafeX/docker-php-nginx#23]
What will be the configuration of php-fpm for 10000 users (Realtime Users)

**Comment by TrafeX** [comment]
Hi @synetalsolutions,

:sweat_smile: in theory you can change the [max_children](https://github.com/TrafeX/docker-php-nginx/blob/master/config/fpm-pool.conf#L33) to 10000 and raise the `max_requests` as well.
In practice I would recommend splitting the load over multiple replica's of this container. You don't want 10000 users to be depending on one container. You could for example use Kubernetes to spread the load and scale up based the amount of concurrent users.

**Comment by TrafeX** [comment]
I assume this answered your question, let me know if not!
