### ISSUE TITLE
php permission (noob question)

### ISSUE THREAD

**Issue by thereapsz** [TrafeX/docker-php-nginx#24]
Does everything run under the nobody user? so php should be able to run mkdir in the html folder?
php-fpm run as nobody aswell?

Sorry about "noob" question.

**Comment by TrafeX** [comment]
Hi @thereapsz,

Yes that's correct, everything runs under the `nobody` user and if you want to create folders or files via PHP, it needs to have the right permissions to do so.

**Comment by TrafeX** [comment]
I assume this is resolved and close the issue. If not, feel free to leave a comment!
