### ISSUE TITLE
Missing composer vendor folder

### ISSUE THREAD

**Issue by larron** [TrafeX/docker-php-nginx#28]
When attempting to build from this image and use composer as the documentation suggests, you'll come up short and discover that the vendor folder created by composer will never be written into  /var/www/html

This is broken because of the VOLUME /var/www/html in the base image, IE this repository.

Removing the VOLUME declaration from the base image will fix this issue.

**Comment by TrafeX** [comment]
Hi @larron,

I'm not sure why the VOLUME declaration conflicts with running composer. Can you give an example?

**Comment by whnunlife** [comment]
@TrafeX I'm seeing the same issue.  Sample of what I'm trying to do...

```
FROM composer:latest AS composer
FROM trafex/alpine-nginx-php7:latest

COPY --from=composer /usr/bin/composer /usr/bin/composer

USER root

#Install php packages for composer
RUN apk add --no-cache php7-simplexml php7-tokenizer php7-xmlwriter

USER nobody

#Set working directory
WORKDIR /var/www/html

COPY --chown=nobody site .
COPY --chown=nobody site/development.env .env
RUN composer install --optimize-autoloader --no-interaction --no-progress

RUN ls -al

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8080

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
```

After running compose, the vendor folder is never created. Now, if I start up the Dockerfile, and execute into the running container, I can run composer install from the `var/www/html` directory, then it get's added correctly.

**Comment by larron** [comment]
@whnunlife that's a perfect example of what is happening.  Removing the VOLUME declaration from the base will fix the issue.

**Comment by TrafeX** [comment]
Thanks, you both are absolutely right. It's because the `RUN` instruction is executed in a container with an anonymous volume and that volume is discarded after the command is executed, deleting all contents written to `/var/www/html`.

I've removed the VOLUME instruction in https://github.com/TrafeX/docker-php-nginx/releases/tag/1.6.0

**Comment by whnunlife** [comment]
@TrafeX Thanks!
