### ISSUE TITLE
/bin/sh: pecl: not found

### ISSUE THREAD

**Issue by yunus89** [TrafeX/docker-php-nginx#29]
Using this Dockerfile, i added another needed package by my application called `opencensus-alpha`. The package is installed using `pecl`. 

So by adding the following line of code in the already existing Dockerfile 
    `RUN pecl install opencensus-alpha`
an error was thrown 
        
    Step 4/18 : RUN pecl install opencensus-alpha
     ---> Running in 4d0f464fb79c
    /bin/sh: pecl: not found
    The command '/bin/sh -c pecl install opencensus-alpha' returned a non-zero code: 127

How can i install `pecl` or packages installed through it with this Dockerfile

**Comment by TrafeX** [comment]
Hi @yunus89 ,

Pecl is part of the `php7-pear` package. You can instal this package with
```
RUN apk add --no-cache php7-pear
```
Then you should be able to run pecl.

**Comment by yunus89** [comment]
For `opencensus-alpha` to be installed via `pecl` following are needed

    RUN apk add --no-cache php7-dev php7-pear
    RUN apk add autoconf gcc g++ make
    RUN pecl install opencensus-alpha
