### ISSUE TITLE
Missing extensions for PHP7

### ISSUE THREAD

**Issue by guoyanjun5** [TrafeX/docker-php-nginx#3]
`
ERROR: unsatisfiable constraints:
  php7-mongodb (missing):
    required by: world[php7-mongodb]
The command '/bin/sh -c apk --no-cache add php7 php7-fpm php7-mysqli php7-json php7-openssl php7-curl     php7-zlib php7-xml php7-phar php7-intl php7-dom php7-xmlreader php7-ctype     php7-mbstring php7-gd php7-mongodb nginx supervisor curl' returned a non-zero code: 1
`

**Comment by TrafeX** [comment]
Hi,

You're trying to install php7-mongodb? I see here it's in the testing repository: https://pkgs.alpinelinux.org/packages?name=php7-mongodb&branch=&repo=&arch=&maintainer=
Which means you should add that repository to install it, like this:

```
RUN apk --no-cache add php7 php7-fpm php7-mysqli php7-json php7-openssl php7-curl \
    php7-zlib php7-xml php7-phar php7-intl php7-dom php7-xmlreader php7-ctype \
    php7-mbstring php7-gd php7-mongodb nginx supervisor curl \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/ \
    --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing/
```

Be advised that (as the name implies) this is a testing repository and maybe not as stable as the regular repository.

Cheers!

**Comment by guoyanjun5** [comment]
thank you

**Comment by Nottt** [comment]
```
2019/07/20 16:38:44 [error] 9#9: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function session_start() in /var/www/html/includes/header.php:9
Stack trace:
```

I'm having this error...would it be possible to add php7-session to the docker image?
