### ISSUE TITLE
php7.4?

### ISSUE THREAD

**Issue by adamgyongyosi** [TrafeX/docker-php-nginx#33]
hy can you create php 7.4 support?
https://github.com/docker-library/repo-info/blob/master/repos/php/remote/7.4-fpm-alpine.md

**Comment by TrafeX** [comment]
Hi @adamgyongyosi,

For that I'm depending on when Alpine Linux releases PHP7.4 packages. There are many other ways to get PHP7.4 running in a container, but this image is using the Alpine Linux packages.
Unfortunaly I don't have a timeline when PHP7.4 will be added.

**Comment by adamgyongyosi** [comment]
Thanks for the reply, have a good time

**Comment by TrafeX** [comment]
Thanks, you too!
