### ISSUE TITLE
Customize Logging?

### ISSUE THREAD

**Issue by sonicnkt** [TrafeX/docker-php-nginx#37]
Hi,
Im currently testing your image with the rss feed aggregator sefloss.
There are selfoss images available but these are quite old and i wanted to run the latest nightly builds.

Anyway i got everything working (had to tweek settings and add a few modules tho) but i have one last issue.
the full debug logs of selfoss are piped into the docker logs and these are getting huge quite fast. 
I have configured the log level for selfoss to error only but this seems to be ignored for the container logs and only apply to its own log files. 
Is there a way to custimize the logging for the php application and where would i configure this.

Sorry if this is more of a general question and maybe not really related to your image.

**Comment by TrafeX** [comment]
Hi @sonicnkt,

Are you sure you've set `logger_level` to `ERROR` or higher in the `config.ini`? 
According to the docs this should also apply on what's send to `/dev/stderr`.

Can you show a snippet of the logs output you currently see?

**Comment by sonicnkt** [comment]
hi @TrafeX ,
Im running currently a nightly snapshot that is 2 weeks old so i will update this to the latest version before testing this again and before uploading a snippet of the logfile. 
But it sounds like this is a problem with selfoss itself that is not considering the loglevel for the /dev/stderr output but only the builtin logger and your dockerimage is just piping everything for /dev/stderr to the docker log daemon.

**Comment by sonicnkt** [comment]
Ok just updated to the latest version of selfoss and the issue still persists.
Docker Logs are full of DEBUG messages when updating the feeds:

`[2020-06-04 10:27:16] selfoss.graby.DEBUG: [MORE CONTENT]`

Graby is used to get fulltext rss and those DEBUG logs are huge as it contains almost the whole page its trying to scrape.  I will create an issue about the logging to /dev/stderr on its project page. Thanks for pointing me in the right direction.

**Comment by TrafeX** [comment]
I see the upstream bug you reported was resolved and a new version is published. Can you try again with version 2.19?

**Comment by TrafeX** [comment]
I assume this is resolved, if not let me know!
