### ISSUE TITLE
Change UID and GID of user nobody in runtime

### ISSUE THREAD

**Issue by EdyTheCow** [TrafeX/docker-php-nginx#43]
Is there currently an easy way to change the UID and GID of user nobody in runtime? What I wanna achieve is ability to change its IDs to match host using environment variables rather than having to build the image itself in order to change it.

**Comment by TrafeX** [comment]
Hi @EdyTheCow,

I don't know of a way without building the container yourself.
What you could do is pass on `UID` & `GID` as build args and change the ID's of the nobody user to those in the Dockerfile;
```
    usermod -u ${UID} nobody
    groupmod -o -g ${GID} nobody
```

**Comment by EdyTheCow** [comment]
Build args work fine, but you have to build the image anyway which is what I was trying to avoid. It seems like there's way too much work in order to accomplish this. Thanks for the reply anyway!
