### ISSUE TITLE
Php 7.4

### ISSUE THREAD

**Issue by StephanKrauss** [TrafeX/docker-php-nginx#44]
Hello,

i need php7.4.

Is there a way ?

Your sincerly

Stephan

**Comment by erseco** [comment]
This docker image is using the latest stable Alpine Linux version (3.12) which uses php7.3. You must wait until the next Alpine Linux versión 3.13. For testing purposes you can use my own fork of this repo using that uses unstable Alpine Linux version (edge) but never use it on a production environment. 

To run the edge version with php7.4: `docker run -p 8080:8080 erseco/alpine-php7-webserver:edge`

**Comment by TrafeX** [comment]
Hi @StephanKrauss,

Yes what @erseco is saying is correct, this image is depending on what Alpine Linux is offering in it's repositories which is currently PHP7.3.
PHP7.4 is in the upcoming release, but it can take some time before it's released as stable.

In the meantime you can use the image @erseco is mentioning or have a look at the official PHP image, that one also has an Alpine Linux build: https://hub.docker.com/_/php

**Comment by bisko** [comment]
I've been messing around with this for more time than I'd like to admit, as I wanted 7.4 support, but didn't want to handle an additional web-server configuration and such and other images had their issues that I didn't want to dig too much into.

Until Alpine and this image is updated, one can do a very hacky "upgrade" of PHP to 7.4 by adding the following to their `Dockerfile`:

```Dockerfile
FROM trafex/alpine-nginx-php7 AS app

USER root

# Until the base image upgrades to PHP7.4/alpine 3.13
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
RUN apk update && apk del php7 php7-fpm php7-opcache php7-mysqli php7-json php7-openssl php7-curl \
                          php7-zlib php7-xml php7-phar php7-intl php7-dom php7-xmlreader php7-ctype php7-session \
                          php7-mbstring php7-gd
RUN apk --no-cache add php7 php7-fpm php7-opcache php7-mysqli php7-json php7-openssl php7-curl \
                              php7-zlib php7-xml php7-phar php7-intl php7-dom php7-xmlreader php7-ctype php7-session \
                              php7-mbstring php7-gd

### END PHP7.4 hacks
```

This would add the `edge` repositories and reinstall the PHP7 packages defined by the image, so they get upgraded to their latest versions in `edge`.

It's not a very flexible approach, but I tested out with `apk upgrade php7*`, and while it did upgrade the packages properly, it broke networking pretty badly. Most external hosts stopped resolving in the container (only several "cached" hosts were resolving properly).

**Comment by TrafeX** [comment]
I'm happy to report that Alpine Linux 3.13 is out and this image now has PHP7.4!
https://github.com/TrafeX/docker-php-nginx/releases/tag/1.10.0
