### ISSUE TITLE
start container with volume under windows 10.x

### ISSUE THREAD

**Issue by StephanKrauss** [TrafeX/docker-php-nginx#45]
Hello,

i'm a beginner in docker.
I will include my own scripts.
I start the container:
 docker run -p 80:8080 -v c:/xampp1/htdocs/test/:/var/www/html trafex/alpine-nginx-php7

In my directory 'test' is the index.php.

When i call 'http://localhost/index.php' i get the error '404 Not Found'.

172.17.0.1 - - [13/Jul/2020:12:52:52 +0000] "GET /index.php HTTP/1.1" 404 125 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0" "-" 0.000 - . -

Anybody a idea ?

Your sincerly

Stephan

**Comment by StephanKrauss** [comment]
Hello,

i hope this is the solution:
docker run -p 80:8080 -v C:/test/alpine-php7-webserver/public:/var/www/html erseco/alpine-php7-webserver

Your sincerly

Stephan

**Comment by TrafeX** [comment]
Hi @StephanKrauss,

So you solved your issue?
What solved it? Using `erseco/alpine-php7-webserver` or changing the path of the volume mount?

**Comment by PeterOlivera** [comment]
I was able to use it like this

docker run -p 80:8080 -v //C/MyFolder:/var/www/html trafex/alpine-nginx-php7

basically using the //C/MyFolder for the folder I have on C:\MyFolder where my pages are located.

**Comment by TrafeX** [comment]
Great, glad that it worked!

**Comment by DroneZzZko** [comment]
Actually, I have the same problem:
```terminal
wget -c https://github.com/symfony/demo/archive/refs/tags/v1.7.1.tar.gz -O - | tar -xz
cd demo-1.7.1 && composer install
docker run -p 8080:8080 -v ~/demo-1.7.1:/var/www/html trafex/php-nginx
```
http://localhost:8080/ returns **403 Forbidden**

In logs I see:
```terminal
2021-07-12 21:56:07,419 INFO supervisord started with pid 1
2021-07-12 21:56:08,422 INFO spawned: 'nginx' with pid 7
2021-07-12 21:56:08,423 INFO spawned: 'php-fpm' with pid 8
[12-Jul-2021 21:56:08] NOTICE: fpm is running, pid 8
[12-Jul-2021 21:56:08] NOTICE: ready to handle connections
2021-07-12 21:56:09,441 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021-07-12 21:56:09,441 INFO success: php-fpm entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2021/07/12 21:56:14 [error] 9#9: *1 directory index of "/var/www/html/" is forbidden, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost:8080"
172.17.0.1 - - [12/Jul/2021:21:56:14 +0000] "GET / HTTP/1.1" 403 186 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36" "-" 0.000 - . -
```
