### ISSUE TITLE
php and xdebug

### ISSUE THREAD

**Issue by StephanKrauss** [TrafeX/docker-php-nginx#46]
Hello,

I want to add xdebug to php. Does Alpine have an xdebug package?

Best regards

Stephan

**Comment by StephanKrauss** [comment]
Hello,

i have add php7-pecl-xdebug.
When i call phpinfo() , i missing Xdebug.

Here the part from the dockerfile:

RUN apk --no-cache add php7 php7-fpm php7-opcache php7-mysqli php7-json php7-openssl php7-curl \
    php7-zlib php7-xml php7-phar php7-intl php7-dom php7-xmlreader php7-ctype php7-session php7-pecl-xdebug \
    php7-mbstring php7-gd nginx supervisor curl && \
    rm /etc/nginx/conf.d/default.conf

I need a information for the php.ini. What is the correct setting in the php.ini ?

Your sincerly

Stephan

**Comment by TrafeX** [comment]
Hi @StephanKrauss,

You need to add the `php7-xdebug` package to be installed and need to enable the extension.
It's not enabled by default, so you can do this in your Dockerfile as follows;

```
RUN echo 'zend_extension=xdebug.so' > /etc/php7/conf.d/xdebug.ini
```

**Comment by StephanKrauss** [comment]
Hello,

can i use in the Dockerfile ?
------------------
RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.collect_return=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.collect_includes=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.show_mem_delta=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.collect_params=4" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.trace_format=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=1" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_host='localhost'" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_port=9000" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_handler='dbgp'" >> /usr/local/etc/php/conf.d/xdebug.ini
---------------------

Your sincerly

Stephan

**Comment by TrafeX** [comment]
Hi @StephanKrauss,

Did yo saw my previous comment? https://github.com/TrafeX/docker-php-nginx/issues/46#issuecomment-659645056
You don't need the pecl package, you can just add `php7-xdebug`:
```
RUN apk add --no-cache php7-xdebug
```
To configure it, you need to add the echo's you have to this file: `/etc/php7/conf.d/xdebug.ini`
The file location you are using is incorrect.

**Comment by TrafeX** [comment]
I'm going to close this issue due to inactivity. If you still need help, please let me know so I can re-open it!
