### ISSUE TITLE
PDO is not installed

### ISSUE THREAD

**Issue by ddliu** [TrafeX/docker-php-nginx#5]
Class PDO does not exist

![image](https://user-images.githubusercontent.com/797146/42612767-bdc61a18-85cf-11e8-9619-6c38e2192fe8.png)

**Comment by lmorel3** [comment]
I also tried to install PDO by adding this line `RUN apk add --no-cache php7-pdo` to my Dockerfile, but it doesn't work. Perhaps, I've a file **00_pdo.ini** inside _/etc/phpp6/conf.d_

I think it could be a good idea to add PDO directly in the project Dockerfile. This library is really often used..

Thanks

**Comment by lmorel3** [comment]
I finally make it work! It was a bit tricky but here's my Dockerfile : 

```
FROM trafex/alpine-nginx-php7
RUN rm -rf /var/www/html/*

RUN apk add --no-cache php7-pdo php7-sqlite3 php7-pdo_sqlite

WORKDIR /var/www/html
COPY app/ /var/www/html/
```

For MySQL, simply add _php7-pdo_mysql_, not simply _php7-mysql_ ... !


Hope it'll help you.

**Comment by TrafeX** [comment]
Yes that should do it! :+1: 
Although you don't need to add the dependencies yourself (like php-7-pdo and php7-sqlit3). You can just add one of these packages: https://pkgs.alpinelinux.org/packages?name=php7-pdo_*&branch=edge&arch=x86_64 to include the desired database API.

This example Dockerfile already includes `php7-mysqli` to communicate with a database so I will not add PDO to it as well. If you want to use PDO; add the right package to the Dockerfile and remove `php7-mysqli`.

If you're not sure what API to use for talking to the database, see this comparison: http://php.net/manual/en/mysqlinfo.api.choosing.php

**Comment by jordie23** [comment]
There's a new issue since the user is changed to `nobody` now. I found this works though (for anyone stumbling upon this thread):

```
FROM trafex/alpine-nginx-php7
USER root
RUN apk --no-cache add php7-pdo_mysql
USER nobody
```
