### ISSUE TITLE
gzip_min_length

### ISSUE THREAD

**Issue by maggie0002** [TrafeX/docker-php-nginx#50]
`gzip on;`is a nice recent addition to the NGINX config file. There seems to be quite a broad consensus though that setting the gzip_min_length higher than its default is makes it more effectives, as compression of smaller files can sometimes make them bigger. 

NGINX's own documentation provides some example configurations which seem to be quite widely held to be more suitable: 

`gzip_min_length 1000;`

http://nginx.org/en/docs/http/ngx_http_gzip_module.html#gzip_vary
https://docs.nginx.com/nginx/admin-guide/web-server/compression/

Something to explore and consider. 

@erseco

**Comment by TrafeX** [comment]
Hi @maggie0002,

Thank you for the suggestion. I agree it's probably better to set this to a higher value.
But it's a micro-optimization and if you're in the situation to tweak this, you probably already forked this repository and tweaked a lot of other settings as well 😉
I try to use sane defaults and leave it up to nginx in this case to set those defaults.
