### ISSUE TITLE
worker_processes auto; in NGINX config file

### ISSUE THREAD

**Issue by maggie0002** [TrafeX/docker-php-nginx#52]
The `worker_processes auto;` setting in the NGINX config file aims to identify the number of CPU cores on the device and start a worker process for each. One process per CPU core is recommended: https://www.nginx.com/blog/tuning-nginx/

The jury was out for a while on whether this works in docker, but a quick test on my system, running without any worker_process setting starts 1 as expected, running on auto starts 4 as per the number of cores so seems to be doing its job. 

Something to consider including.

**Comment by TrafeX** [comment]
Hi @maggie0002 ,

Thank you for the suggestion, I've changed it in this release: https://github.com/TrafeX/docker-php-nginx/releases/tag/1.9.0
