### ISSUE TITLE
Proposed alternative for SCRIPT_FILENAME

### ISSUE THREAD

**Issue by maggie0002** [TrafeX/docker-php-nginx#56]
I had some issues using the alias directive on the nginx config files and loading php files. Turns out it was an issue with the SCRIPT_FILENAME attribute used in this repo. This post explains more and recommends an alternative that fixed it for me. 

https://serverfault.com/a/922596

Posting here as a proposed change but for smarter people than I to work out any implications I may have missed.

**Comment by TrafeX** [comment]
Hi @maggie0002,

Thank you for pointing this out.
I believe you should only consider this when using `alias` instead of the current config where we use `root`.

I'll close this issue, if other people experience issues with the current `SCRIPT_FILENAME` value; feel free to open a new issue.
