### ISSUE TITLE
php cli commands are not working since it is php8

### ISSUE THREAD

**Issue by surendhar153** [TrafeX/docker-php-nginx#58]
in the latest php8 update php cli commands are not working

```
/var/www/html $ php -v
/bin/sh: php: not found
/var/www/html $ php8 -v
PHP 8.0.2 (cli) (built: Feb  5 2021 00:39:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.2, Copyright (c), by Zend Technologies
/var/www/html $ 
```

Due to this wp cli is not working - https://make.wordpress.org/cli/handbook/guides/installing/ 
```
=> ERROR [11/11] RUN wp core download --version=5.7.1 --locale=en_US                                                                                                                0.3s
------
 > [11/11] RUN wp core download --version=5.7.1 --locale=en_US:
#16 0.264 env: can't execute 'php': No such file or directory
```

**Comment by TrafeX** [comment]
Hi @surendhar153,

Thank you for reporting this. It seems intended behavior, see: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12308
But it indeed makes sense to make `php8` as `php` available for programs that depend on it.
I've fixed this in 2.0.2 https://github.com/TrafeX/docker-php-nginx/releases/tag/2.0.2
