### ISSUE TITLE
Customize root directory by env var

### ISSUE THREAD

**Issue by mxmorin** [TrafeX/docker-php-nginx#69]
Should be great if root directive on nginx.conf could be customized by an ENV var in the Dockerfile.
In my case, my Symfony applications must have a root to /var/www/html/public

**Comment by TrafeX** [comment]
Hi @mxmorin,

I understand why you would want this, but this container isn't meant to be dynamically configured for every application.
It's an example which you can fork/copy and modify to your needs. That way it stays as simple as possible and easily to understand and modify.

**Comment by erseco** [comment]
Hi @mxmorin if you need to use ENV vars you can use my own fork of the marvelous @TrafeX container: https://github.com/erseco/alpine-php-webserver

But as @TrafeX said, if you need more changes you should fork and modify the original "docker-php-nginx" container  to fit your needs.

Hope it helps, best regards!
