### ISSUE TITLE
all services run as root

### ISSUE THREAD

**Issue by thouters** [TrafeX/docker-php-nginx#7]
This is a start for a dockerfile, thanks.

It should however include more stuff from https://wiki.alpinelinux.org/wiki/Nginx_with_PHP

**Comment by TrafeX** [comment]
Hi @thouters, thanks for your feedback!
I agree with what you mention in the title that we should avoid running services as root. Coincidentally I was already working on that and if it works out nicely I will push that.

For the document you're sharing from Alpine Linux I don't really see any improvements I can take out of it. Do you have any specific suggestions?

**Comment by TrafeX** [comment]
I've changed the services to run under a non-privileged user, see https://github.com/TrafeX/docker-php-nginx/commit/659806c6d06edfe08163243fc0ac9bfc7ca0fa81

**Comment by TrafeX** [comment]
I'm closing this issue. Let me know if you see any other improvements I can do! Thanks!
