### ISSUE TITLE
Switch to Root user return 403 forbidden

### ISSUE THREAD

**Issue by Raye3** [TrafeX/docker-php-nginx#71]
I tried switching to root user, and change the ownership of directories and files to the root user, but when running a php file, get 403. any ideas ?

**Comment by TrafeX** [comment]
Hi @Raye3 ,

Yes if you remove the switch to the `nobody` user in the `Dockerfile` PHP-FPM isn't able to start.
It then requires your to set a user and group (https://www.php.net/manual/en/install.fpm.configuration.php#user) in the fpm-pool.conf. And that user can't be root.

**Comment by TrafeX** [comment]
I'm closing this issue, let me know if you need any more help!
