### ISSUE TITLE
How to install imageick for PHP 8?

### ISSUE THREAD

**Issue by bhaidar** [TrafeX/docker-php-nginx#76]
Hi,

Any idea on how to include some instructions on how to add imageick extension using this dockerfile.

Many thanks
Bill

**Comment by TrafeX** [comment]
This seems to be resolved! :+1:

**Comment by azlux** [comment]
Little suggestion here to avoid build our own docker.
Can the php extensions be installed with a environnement variable ?
This can be great. You put a list on your variable, and the image install it at start.

**Comment by erseco** [comment]
IMHO is not a good idea install packages in run time, much better to do on build time.

You can extend @TrafeX container to suit your needs, in the readme.md file you have the info

Best!
