### ISSUE TITLE
Error upon container creation

### ISSUE THREAD

**Issue by a-private-user** [TrafeX/docker-php-nginx#83]
Hi,

first of all cuedos and thank you for this nice image! I currently use it to host an intranet web page and process a php script.
It used to work fine until version 2.4.0.

Now with the latest version, containers with this image can no longer be created. This is how to replicate:
1. As said, version 2.4.0 works perfectly. 
2. Environment: I do run this on a Raspberry Pi 4. OS is PiOS 64bit with docker installed. 
3. At CLI level, enter "docker run -p 4567:8080 trafex/php-nginx"
4. Expected result: Container successfully created
5. Current result: No container created. Instead, error message "standard_init_linux.go:228: exec user process caused: exec format error"

It seems there is nothing I can do about this and to me it looks like a flaw in the image. Maybe you can help.
Keep up the good work!
Tom

**Comment by TrafeX** [comment]
Hi @a-private-user,

Do I understand it correctly that `2.4.0` worked fine, but the `latest` tag introduces this issue?
I have an idea what could cause this, I already waited with tagging a new release because of the potential issue.

**Comment by a-private-user** [comment]
Hi Peter,
yes, exactly. I used until now 2.4.0 and that could with a small .yml be instantiated. With the update to trafex/php-nginx:latest, the described error appears. My docker is up to date. For a full picture, I copied my .yml here.
Thanks for your efforts!
Best - Tom

My currently working .yml:

services:
  # Froggit Gateway
  openhab-froggit-gateway:
    image: trafex/php-nginx:2.4.0
    container_name: openhab-froggit-gateway
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - openhab_local
    ports:
      - 8020:8080
    healthcheck:
      test: "curl --silent --fail http://127.0.0.1:8080/fpm-ping"
      interval: 60s
      timeout: 9s
      retries: 3
    volumes:
      - froggit_gateway:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

**Comment by TrafeX** [comment]
Hi @a-private-user,

I've made a change (removed the Go version of supervisor which was included from an image that doesn't support multi-arch builds), could you pull the `latest` tag and try again?

**Comment by a-private-user** [comment]
Hi TrafeX,
great! I changed the .yml to ":latest" and now everything is working great again. 
Thank you for the quick fix!
Tom
