### ISSUE TITLE
OpenShift - Permission Denied

### ISSUE THREAD

**Issue by fernandoamorim30** [TrafeX/docker-php-nginx#86]
Hello,

I`m trying run this project on OpenShift and  has returned this message after container created:

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/62866726/157148202-3df109da-038a-4cbc-bd61-6beda06db8db.png">

Someone has haved this issue before?

Thanks! 👊

**Comment by lstellway** [comment]
Hey @fernandoamorim30 👋 

Looks like a permissions issue. 
Do you have this line in your `Dockerfile` _([reference](https://github.com/TrafeX/docker-php-nginx/blob/b3ee5d84c0a2bc12ac8180e365f9afca326523e4/Dockerfile#L45))_?

```
RUN chown -R nobody.nobody /var/www/html /run /var/lib/nginx /var/log/nginx
```

@TrafeX 

Just using this issue as an opportunity to thank you for the work on this image 🙏 
It works wonderfully 💯

**Comment by TrafeX** [comment]
Hi @fernandoamorim30,

Could you post the deployment yaml from OpenShift? I suspect the filesystem has a different owner specified.

@lstellway Thank you for the kind words! :pray:

**Comment by TrafeX** [comment]
Hi @fernandoamorim30,

I'm going to close this issue due to inactivity. Let me know if you still experience this and can share the information I requested above.
