### ISSUE TITLE
Permission Problem

### ISSUE THREAD

**Issue by olaseyo** [TrafeX/docker-php-nginx#87]
I kept getting the error below after following the instructions.
/var/www/html/vendor does not exist and could not be created. 

A portion of my docker file

# Make sure files/folders needed by the processes are accessable when they run under the nobody user
RUN chown -R nobody.nobody /var/www/html && \
  chown -R nobody.nobody /run && \
  chown -R nobody.nobody /var/lib/nginx && \
  chown -R nobody.nobody /var/log/nginx

**Comment by TrafeX** [comment]
Hi @olaseyo,

Can you post the full `Dockerfile` and the command you run to start the docker container?

**Comment by TrafeX** [comment]
Hi @olaseyo 

I'm going to close this issue due to inactivity. Let me know if you still experience this and can share the information I requested above.
