### ISSUE TITLE
How to troubleshoot permissions issues

### ISSUE THREAD

**Issue by TT-IPIP** [TrafeX/docker-php-nginx#88]
```
Warning: mkdir(): Permission denied in /var/www/html/index.php on line 19
Error
Failed to create _files

**Comment by TrafeX** [comment]
Hi @TT-IPIP,

Can you post your `Dockerfile` and the command you execute to run the container?

**Comment by TrafeX** [comment]
Hi @TT-IPIP 

I'm going to close this issue due to inactivity. Let me know if you still experience this and can share the information I requested above.
