### ISSUE TITLE
Deprecated dependency php8-json

### ISSUE THREAD

**Issue by den-dev-icmy** [TrafeX/docker-php-nginx#89]
php8-json dependency is no needed now.
https://github.com/TrafeX/docker-php-nginx/blob/b3ee5d84c0a2bc12ac8180e365f9afca326523e4/Dockerfile#L19

proof: https://www.php.net/manual/en/json.installation.php
> As of PHP 8.0.0, the JSON extension is a core PHP extension, so it is always enabled.

**Comment by TrafeX** [comment]
Hi @den-dev-icmy,

Thank you, you're right! I've removed the json extension from the Dockerfile.
