### ISSUE TITLE
Sqlite usage with PDO

### ISSUE THREAD

**Issue by letshin** [TrafeX/docker-php-nginx#90]
Hi, I managed to get everything running but have the following error message:

2022/03/27 07:27:33 [error] 9#9: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class "PDO" not found in 

Is there a way to enable sqlite or am I doing something wrong?

The application calls for an sqlite database this way:

$db = new PDO('ls ~/syncthing/selfoss/sqlite/selfoss.db');

php.net/manual/en/ref.pdo-sqlite.php suggests that libsqlite needs to be installed... how do I do this for a container please?

**Comment by TrafeX** [comment]
Hi @letshin,

You need to install the PDO and sqlite driver extensions;
`RUN apk add --no-cache php8-pdo php8-pdo_sqlite`

Also take a look at the argument you're giving to `new PDO()`, you probable want this;
`$db = new PDO('sqlite:~/syncthing/selfoss/sqlite/selfoss.db');`
(not sure if the `~` is going to work there)

**Comment by herbbetz** [comment]
Hi Tim, thanks for your "simple" docker image, albeit it seemed nonetheless difficult for a non-expert like me. I had written a php application, which worked no problem in xampp (apache, I know... php-Version 8), but failed with your image with no explaining error message. After several hours, I found the reason in the above answer to @letshin: no php8-pdo_sqlite. I have tried multiple times to "docker build" your application, using php8-pdo and php8-sqlite3 and a lot of other php modules, which names I took from the xampp, but several had no php8-equivalent, e.g. no php8-date, no php8-filter and many more.

Can I pose some questions occuring to me in those hours:
1) What about the php-Modules, that have no php8-equivalent?
2) Why does nginx not work any more, when I comment out the "nobody" lines in the Dockerfile? It hindered me to install new packages from inside the container shell.
3) Why this supervisor /python3 in the simplified image? https://pypi.org/project/supervisor/ I found not very enlightening.

Thanks for reading,
H. Betz

**Comment by herbbetz** [comment]
P.S.: maybe another cool idea:

if there is already python3 in the image, could you not configure python-cgi in nginx? Maybe python modules are easier to supplement than php-modules...?

**Comment by TrafeX** [comment]
Hi @herbbetz,

This Docker image requires a certain level of knowledge about the PHP, Nginx and Docker ecosystems.
It's a template which you need to tweak to optimize it for your use-case. Based on your reaction this might not be the best option for you.
I know there are a lot of Docker images that are more 'batteries included', they have all the PHP extensions preinstalled.
Those might be more suited for you. For example; https://github.com/thecodingmachine/docker-images-php

**Comment by herbbetz** [comment]
Hi Tim, thanks a lot for telling me about thecodingmaschine. Even with few background, I got your image working now using the above sqlite addition. The container is getting lots of spam hits and user nobody seems a good idea... Thanks again for your work...

**Comment by TrafeX** [comment]
You're welcome! :+1:
