### ISSUE TITLE
sh and bash

### ISSUE THREAD

**Issue by pere000** [TrafeX/docker-php-nginx#94]
Docker-PHP-Nginx does not allow 'bash', only 'sh'. Is there a way to use bash instead of sh? Have you considered adding 'bash' in the future? Thanks for your docker.

**Comment by TrafeX** [comment]
Hi @pere000,

That's intended to keep the image small. Bash has a larger footprint and most of the time you don't need the features that bash brings in a container. You can always fork this repo and add `bash` to the list of installed applications: https://github.com/TrafeX/docker-php-nginx/blob/2.6.0/Dockerfile#L9
