### ISSUE TITLE
Request: Add PDO support

### ISSUE THREAD

**Issue by icebrian** [TrafeX/docker-php-nginx#97]
Firstly, thanksfor this container, very useful indeed!

For my specific need I had to build my own container based on your image to add PDO support https://github.com/icebrian/php-nginx-pdo/blob/main/Dockerfile

May-be consider adding it by default? Anyways, if not no worries.

**Comment by TrafeX** [comment]
Hi @icebrian,

Thank you for the compliment!
I'm trying to keep this image as small as possible, so the number of extensions included are limited.
PDO is very popular, but what specific driver you need depends; some use MySQL, some PostgreSQL and some don't use PDO at all. So not an extension that will benefit everyone when added unfortunately.
