### ISSUE TITLE
about server.conf and nginx.conf

### ISSUE THREAD

**Issue by youyifentian** [TrafeX/docker-php-nginx#98]
i can mount a configuration file for nginx but i must enter the container edit the nginx.conf file
However, it doesn't make me feel comfortable
because，if i want to use the default port 8080 settings，I have to get into the container，edit or delete some code of nginx.conf file，so that would make  it look useless for mount a configuration file

so why not 
move some code of nginx.conf to /etc/nginx/conf.d/server.conf or /etc/nginx/conf.d/default.conf  for default config
some code like:
server {
        listen [::]:8080 default_server;
        listen 8080 default_server;
        server_name _;
       ..............

so We can edit server.conf or default.conf  without entering the container

**Comment by TrafeX** [comment]
Hi @youyifentian,

Thank you. I'll consider changing this since more people are asking the same question.

**Comment by yani** [comment]
Hi. It would be nice to separate `http{}` and `server{}` in the nginx config so when we set a custom `server{}` the default one is not used.

**Comment by TrafeX** [comment]
Hi @youyifentian and @yani ,

It it took a while, but the nginx config is now split up thanks to https://github.com/TrafeX/docker-php-nginx/pull/109
